steps:
  # - name: gcr.io/cloud-builders/git
  #   entrypoint: /bin/bash
  #   args:
  #     - -exc
  #     - |
  #       # Cloud Build x GitHub integration uses source archives to fetch
  #       # the source, rather than Git source fetching, and as a consequence
  #       # does not include the .git/ directory. As a workaround, we clone
  #       # the repository to grab the .git directory.
  #       git clone 'https://github.com/jonathanmetzman/cifuzz-external-example' tmp
  #       git -C tmp fetch origin "$COMMIT_SHA"
  #       git -C tmp checkout -qf FETCH_HEAD
  #       mv tmp/.git .git
  #       rm -rf tmp
  - name: gcr.io/oss-fuzz-base/cifuzz-build-fuzzers:v1
    env:
      - 'LANGUAGE=c++'
      - 'WORKSPACE=/builder/home'
      - 'PROJECT_SRC_PATH=/workspace'
      - 'REPOSITORY=cifuzz-external-example'
      - 'FILESTORE=gsutil'
      - 'CLOUD_BUCKET=gs://metzman-test/'
      - 'UPLOAD_BUILD=True'

  - name: gcr.io/oss-fuzz-base/cifuzz-run-fuzzers:v1
    env:
      - 'LANGUAGE=c++'
      - 'WORKSPACE=/builder/home'
      - 'PROJECT_SRC_PATH=/workspace'
      - 'REPOSITORY=cifuzz-external-example'
      - 'FILESTORE=gsutil'
      - 'CLOUD_BUCKET=gs://metzman-test/'
