name: CIFuzz
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - master
jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout source
     uses: actions/checkout@v2
     id: checkout
     with:
       path: cifuzz-external-example
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
     with:
       project-src-path: 'cifuzz-external-example'
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
     with:
       fuzz-seconds: 600
