name: CIFuzz
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - master
jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, coverage]
   steps:
   - name: echo env vars
     run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_ACTION_REF $GITHUB_ACTION_REF GITHUB_SHA $GITHUB_SHA"
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@cifuzz-ci-env3
     with:
       sanitizer: ${{ matrix.sanitizer }}
       github-token: ${{ secrets.GITHUB_TOKEN }}
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@cifuzz-ci-env3
     with:
       sanitizer: ${{ matrix.sanitizer }}
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}


 Prune:
   runs-on: ubuntu-latest
   steps:
   - name: echo env vars
     run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_ACTION_REF $GITHUB_ACTION_REF GITHUB_SHA $GITHUB_SHA GITHUB_RUN_ID $GITHUB_RUN_ID"
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@cifuzz-ci-env3
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@cifuzz-ci-env3
     with:
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}
       run-fuzzers-mode: 'prune'
