name: CIFuzz
true:
  pull_request:
    paths:
    - '**'
  push:
    branches:
    - master
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: echo env vars
      run: echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_BASE_REF $GITHUB_BASE_REF
        GITHUB_REF $GITHUB_REF GITHUB_HEAD_REF $GITHUB_HEAD_REF GITHUB_ACTION_REF
        $GITHUB_ACTION_REF GITHUB_SHA $GITHUB_SHA"
    - id: build
      name: Build Fuzzers (${{ matrix.sanitizer }})
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@docker-registry
      with:
        allowed_broken_targets_percentage: 100
        dry-run: false
        oss-fuzz-project-name: cifuzz-example
        sanitizer: ${{ matrix.sanitizer }}
    - id: run
      name: Run Fuzzers (${{ matrix.sanitizer }})
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@docker-registry
      with:
        dry-run: false
        fuzz-seconds: 600
        oss-fuzz-project-name: cifuzz-example
        sanitizer: ${{ matrix.sanitizer }}
    - if: failure() && steps.build.outcome == 'success'
      name: Upload Crash
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./out/artifacts
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address
        - undefined
        - memory

  # BatchFuzzing:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - id: build
  #     name: Build Fuzzers
  #     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@cifuzz-artifacts
  #     with:
  #       build-integration-path: fuzzer-build-integration
  #       oss-fuzz-project-name: cifuzz-external-example
  #   - id: run
  #     name: Run Fuzzers
  #     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@cifuzz-artifacts
  #     with:
  #       build-integration-path: fuzzer-build-integration
  #       fuzz-seconds: 600
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  #       oss-fuzz-project-name: cifuzz-external-example
  #       run-fuzzers-mode: batch
