name: CIFuzz
on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - master

jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, coverage]
   steps:
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@master
     with:
       sanitizer: ${{ matrix.sanitizer }}
       github-token: ${{ secrets.GITHUB_TOKEN }}
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@master
     with:
       sanitizer: ${{ matrix.sanitizer }}
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}
       report-unreproducible-crashes: True
       minimize-crashes: True


 Prune:
   runs-on: ubuntu-latest
   steps:
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@master
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@master
     with:
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}
       run-fuzzers-mode: 'prune'

 Batch:
   runs-on: ubuntu-latest
   steps:
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/external-actions/build_fuzzers@master
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
   - name: Run Fuzzers
     id: run
     uses: google/oss-fuzz/infra/cifuzz/external-actions/run_fuzzers@master
     with:
       fuzz-seconds: 600
       github-token: ${{ secrets.GITHUB_TOKEN }}
       run-fuzzers-mode: 'batch'
